# Generated by Django 4.2 on 2023-05-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="blocked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
