# Generated by Django 4.2 on 2023-05-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_blocked_until"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="blocked_until",
            field=models.DateTimeField(default=None),
        ),
    ]
