# Generated by Django 4.2 on 2023-05-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exemplary',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
