# Generated by Django 4.2 on 2023-05-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exemplaries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exemplary",
            name="default_loan_duration",
            field=models.IntegerField(default=7),
        ),
    ]
