# Generated by Django 4.2 on 2023-05-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplaries', '0002_alter_exemplary_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exemplary',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
