<<<<<<< HEAD
# Generated by Django 4.2 on 2023-05-05 18:08
=======
# Generated by Django 4.2 on 2023-05-05 18:34
>>>>>>> 2671fa5cde2390303465a8cf3087ce7c957f6e90

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("loans", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
<<<<<<< HEAD
=======
        ("loans", "0001_initial"),
>>>>>>> 2671fa5cde2390303465a8cf3087ce7c957f6e90
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
