<<<<<<< HEAD
# Generated by Django 4.2 on 2023-05-04 13:56
=======
# Generated by Django 4.2 on 2023-05-04 13:41
>>>>>>> 3e6da546ca7038d6cab6003a9b6f19f7f321706f

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exemplaries", "0002_exemplary_default_loan_duration"),
        ("loans", "0002_initial"),
=======

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exemplaries', '0002_exemplary_default_loan_duration'),
        ('loans', '0002_initial'),
>>>>>>> 3e6da546ca7038d6cab6003a9b6f19f7f321706f
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name="loan",
            name="return_date",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name="loan",
            unique_together={("exemplary", "user")},
=======
            model_name='loan',
            name='return_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='loan',
            unique_together={('exemplary', 'user')},
>>>>>>> 3e6da546ca7038d6cab6003a9b6f19f7f321706f
        ),
    ]
