# Generated by Django 4.2 on 2023-05-05 13:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0003_alter_loan_return_date_alter_loan_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="loan",
            unique_together=set(),
        ),
    ]
